apiVersion: kuadrant.io/v1beta2
kind: RateLimitPolicy
metadata:
  name: httpbin
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: httpbin
  limits:
    "alice-limit":
      rates:
        - limit: 5
          duration: 10
          unit: second
      when:
        - selector: metadata.filter_metadata.envoy\.filters\.http\.ext_authz.identity.userid
          operator: eq
          value: alice
    "bob-limit":
      rates:
        - limit: 2
          duration: 10
          unit: second
      when:
        - selector: metadata.filter_metadata.envoy\.filters\.http\.ext_authz.identity.userid
          operator: eq
          value: bob